// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/SethCurry/scotty/internal/ent/autorolerule"
)

// AutoRoleRule is the model entity for the AutoRoleRule schema.
type AutoRoleRule struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// RoleID holds the value of the "role_id" field.
	RoleID       string `json:"role_id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AutoRoleRule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case autorolerule.FieldID:
			values[i] = new(sql.NullInt64)
		case autorolerule.FieldRoleID:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AutoRoleRule fields.
func (arr *AutoRoleRule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case autorolerule.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			arr.ID = int(value.Int64)
		case autorolerule.FieldRoleID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role_id", values[i])
			} else if value.Valid {
				arr.RoleID = value.String
			}
		default:
			arr.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AutoRoleRule.
// This includes values selected through modifiers, order, etc.
func (arr *AutoRoleRule) Value(name string) (ent.Value, error) {
	return arr.selectValues.Get(name)
}

// Update returns a builder for updating this AutoRoleRule.
// Note that you need to call AutoRoleRule.Unwrap() before calling this method if this AutoRoleRule
// was returned from a transaction, and the transaction was committed or rolled back.
func (arr *AutoRoleRule) Update() *AutoRoleRuleUpdateOne {
	return NewAutoRoleRuleClient(arr.config).UpdateOne(arr)
}

// Unwrap unwraps the AutoRoleRule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (arr *AutoRoleRule) Unwrap() *AutoRoleRule {
	_tx, ok := arr.config.driver.(*txDriver)
	if !ok {
		panic("ent: AutoRoleRule is not a transactional entity")
	}
	arr.config.driver = _tx.drv
	return arr
}

// String implements the fmt.Stringer.
func (arr *AutoRoleRule) String() string {
	var builder strings.Builder
	builder.WriteString("AutoRoleRule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", arr.ID))
	builder.WriteString("role_id=")
	builder.WriteString(arr.RoleID)
	builder.WriteByte(')')
	return builder.String()
}

// AutoRoleRules is a parsable slice of AutoRoleRule.
type AutoRoleRules []*AutoRoleRule
