// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SethCurry/scotty/internal/ent/autorolerule"
	"github.com/SethCurry/scotty/internal/ent/predicate"
)

// AutoRoleRuleDelete is the builder for deleting a AutoRoleRule entity.
type AutoRoleRuleDelete struct {
	config
	hooks    []Hook
	mutation *AutoRoleRuleMutation
}

// Where appends a list predicates to the AutoRoleRuleDelete builder.
func (arrd *AutoRoleRuleDelete) Where(ps ...predicate.AutoRoleRule) *AutoRoleRuleDelete {
	arrd.mutation.Where(ps...)
	return arrd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (arrd *AutoRoleRuleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, arrd.sqlExec, arrd.mutation, arrd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (arrd *AutoRoleRuleDelete) ExecX(ctx context.Context) int {
	n, err := arrd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (arrd *AutoRoleRuleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(autorolerule.Table, sqlgraph.NewFieldSpec(autorolerule.FieldID, field.TypeInt))
	if ps := arrd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, arrd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	arrd.mutation.done = true
	return affected, err
}

// AutoRoleRuleDeleteOne is the builder for deleting a single AutoRoleRule entity.
type AutoRoleRuleDeleteOne struct {
	arrd *AutoRoleRuleDelete
}

// Where appends a list predicates to the AutoRoleRuleDelete builder.
func (arrdo *AutoRoleRuleDeleteOne) Where(ps ...predicate.AutoRoleRule) *AutoRoleRuleDeleteOne {
	arrdo.arrd.mutation.Where(ps...)
	return arrdo
}

// Exec executes the deletion query.
func (arrdo *AutoRoleRuleDeleteOne) Exec(ctx context.Context) error {
	n, err := arrdo.arrd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{autorolerule.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (arrdo *AutoRoleRuleDeleteOne) ExecX(ctx context.Context) {
	if err := arrdo.Exec(ctx); err != nil {
		panic(err)
	}
}
