// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/SethCurry/scotty/internal/ent/guild"
)

// Guild is the model entity for the Guild schema.
type Guild struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// GuildID holds the value of the "guild_id" field.
	GuildID string `json:"guild_id,omitempty"`
	// WelcomeTemplate holds the value of the "welcome_template" field.
	WelcomeTemplate string `json:"welcome_template,omitempty"`
	// WelcomeChannel holds the value of the "welcome_channel" field.
	WelcomeChannel string `json:"welcome_channel,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GuildQuery when eager-loading is set.
	Edges        GuildEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GuildEdges holds the relations/edges for other nodes in the graph.
type GuildEdges struct {
	// AutoRoleRules holds the value of the auto_role_rules edge.
	AutoRoleRules []*AutoRoleRule `json:"auto_role_rules,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AutoRoleRulesOrErr returns the AutoRoleRules value or an error if the edge
// was not loaded in eager-loading.
func (e GuildEdges) AutoRoleRulesOrErr() ([]*AutoRoleRule, error) {
	if e.loadedTypes[0] {
		return e.AutoRoleRules, nil
	}
	return nil, &NotLoadedError{edge: "auto_role_rules"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Guild) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case guild.FieldID:
			values[i] = new(sql.NullInt64)
		case guild.FieldName, guild.FieldGuildID, guild.FieldWelcomeTemplate, guild.FieldWelcomeChannel:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Guild fields.
func (gu *Guild) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case guild.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			gu.ID = int(value.Int64)
		case guild.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				gu.Name = value.String
			}
		case guild.FieldGuildID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field guild_id", values[i])
			} else if value.Valid {
				gu.GuildID = value.String
			}
		case guild.FieldWelcomeTemplate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field welcome_template", values[i])
			} else if value.Valid {
				gu.WelcomeTemplate = value.String
			}
		case guild.FieldWelcomeChannel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field welcome_channel", values[i])
			} else if value.Valid {
				gu.WelcomeChannel = value.String
			}
		default:
			gu.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Guild.
// This includes values selected through modifiers, order, etc.
func (gu *Guild) Value(name string) (ent.Value, error) {
	return gu.selectValues.Get(name)
}

// QueryAutoRoleRules queries the "auto_role_rules" edge of the Guild entity.
func (gu *Guild) QueryAutoRoleRules() *AutoRoleRuleQuery {
	return NewGuildClient(gu.config).QueryAutoRoleRules(gu)
}

// Update returns a builder for updating this Guild.
// Note that you need to call Guild.Unwrap() before calling this method if this Guild
// was returned from a transaction, and the transaction was committed or rolled back.
func (gu *Guild) Update() *GuildUpdateOne {
	return NewGuildClient(gu.config).UpdateOne(gu)
}

// Unwrap unwraps the Guild entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (gu *Guild) Unwrap() *Guild {
	_tx, ok := gu.config.driver.(*txDriver)
	if !ok {
		panic("ent: Guild is not a transactional entity")
	}
	gu.config.driver = _tx.drv
	return gu
}

// String implements the fmt.Stringer.
func (gu *Guild) String() string {
	var builder strings.Builder
	builder.WriteString("Guild(")
	builder.WriteString(fmt.Sprintf("id=%v, ", gu.ID))
	builder.WriteString("name=")
	builder.WriteString(gu.Name)
	builder.WriteString(", ")
	builder.WriteString("guild_id=")
	builder.WriteString(gu.GuildID)
	builder.WriteString(", ")
	builder.WriteString("welcome_template=")
	builder.WriteString(gu.WelcomeTemplate)
	builder.WriteString(", ")
	builder.WriteString("welcome_channel=")
	builder.WriteString(gu.WelcomeChannel)
	builder.WriteByte(')')
	return builder.String()
}

// Guilds is a parsable slice of Guild.
type Guilds []*Guild
