// Code generated by ent, DO NOT EDIT.

package autorolerule

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the autorolerule type in the database.
	Label = "auto_role_rule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRoleID holds the string denoting the role_id field in the database.
	FieldRoleID = "role_id"
	// Table holds the table name of the autorolerule in the database.
	Table = "auto_role_rules"
)

// Columns holds all SQL columns for autorolerule fields.
var Columns = []string{
	FieldID,
	FieldRoleID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the AutoRoleRule queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRoleID orders the results by the role_id field.
func ByRoleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRoleID, opts...).ToFunc()
}
