// Code generated by ent, DO NOT EDIT.

package guild

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/SethCurry/scotty/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Guild {
	return predicate.Guild(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Guild {
	return predicate.Guild(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Guild {
	return predicate.Guild(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Guild {
	return predicate.Guild(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Guild {
	return predicate.Guild(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Guild {
	return predicate.Guild(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Guild {
	return predicate.Guild(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Guild {
	return predicate.Guild(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Guild {
	return predicate.Guild(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Guild {
	return predicate.Guild(sql.FieldEQ(FieldName, v))
}

// GuildID applies equality check predicate on the "guild_id" field. It's identical to GuildIDEQ.
func GuildID(v string) predicate.Guild {
	return predicate.Guild(sql.FieldEQ(FieldGuildID, v))
}

// WelcomeTemplate applies equality check predicate on the "welcome_template" field. It's identical to WelcomeTemplateEQ.
func WelcomeTemplate(v string) predicate.Guild {
	return predicate.Guild(sql.FieldEQ(FieldWelcomeTemplate, v))
}

// WelcomeChannel applies equality check predicate on the "welcome_channel" field. It's identical to WelcomeChannelEQ.
func WelcomeChannel(v string) predicate.Guild {
	return predicate.Guild(sql.FieldEQ(FieldWelcomeChannel, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Guild {
	return predicate.Guild(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Guild {
	return predicate.Guild(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Guild {
	return predicate.Guild(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Guild {
	return predicate.Guild(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Guild {
	return predicate.Guild(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Guild {
	return predicate.Guild(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Guild {
	return predicate.Guild(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Guild {
	return predicate.Guild(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Guild {
	return predicate.Guild(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Guild {
	return predicate.Guild(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Guild {
	return predicate.Guild(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Guild {
	return predicate.Guild(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Guild {
	return predicate.Guild(sql.FieldContainsFold(FieldName, v))
}

// GuildIDEQ applies the EQ predicate on the "guild_id" field.
func GuildIDEQ(v string) predicate.Guild {
	return predicate.Guild(sql.FieldEQ(FieldGuildID, v))
}

// GuildIDNEQ applies the NEQ predicate on the "guild_id" field.
func GuildIDNEQ(v string) predicate.Guild {
	return predicate.Guild(sql.FieldNEQ(FieldGuildID, v))
}

// GuildIDIn applies the In predicate on the "guild_id" field.
func GuildIDIn(vs ...string) predicate.Guild {
	return predicate.Guild(sql.FieldIn(FieldGuildID, vs...))
}

// GuildIDNotIn applies the NotIn predicate on the "guild_id" field.
func GuildIDNotIn(vs ...string) predicate.Guild {
	return predicate.Guild(sql.FieldNotIn(FieldGuildID, vs...))
}

// GuildIDGT applies the GT predicate on the "guild_id" field.
func GuildIDGT(v string) predicate.Guild {
	return predicate.Guild(sql.FieldGT(FieldGuildID, v))
}

// GuildIDGTE applies the GTE predicate on the "guild_id" field.
func GuildIDGTE(v string) predicate.Guild {
	return predicate.Guild(sql.FieldGTE(FieldGuildID, v))
}

// GuildIDLT applies the LT predicate on the "guild_id" field.
func GuildIDLT(v string) predicate.Guild {
	return predicate.Guild(sql.FieldLT(FieldGuildID, v))
}

// GuildIDLTE applies the LTE predicate on the "guild_id" field.
func GuildIDLTE(v string) predicate.Guild {
	return predicate.Guild(sql.FieldLTE(FieldGuildID, v))
}

// GuildIDContains applies the Contains predicate on the "guild_id" field.
func GuildIDContains(v string) predicate.Guild {
	return predicate.Guild(sql.FieldContains(FieldGuildID, v))
}

// GuildIDHasPrefix applies the HasPrefix predicate on the "guild_id" field.
func GuildIDHasPrefix(v string) predicate.Guild {
	return predicate.Guild(sql.FieldHasPrefix(FieldGuildID, v))
}

// GuildIDHasSuffix applies the HasSuffix predicate on the "guild_id" field.
func GuildIDHasSuffix(v string) predicate.Guild {
	return predicate.Guild(sql.FieldHasSuffix(FieldGuildID, v))
}

// GuildIDEqualFold applies the EqualFold predicate on the "guild_id" field.
func GuildIDEqualFold(v string) predicate.Guild {
	return predicate.Guild(sql.FieldEqualFold(FieldGuildID, v))
}

// GuildIDContainsFold applies the ContainsFold predicate on the "guild_id" field.
func GuildIDContainsFold(v string) predicate.Guild {
	return predicate.Guild(sql.FieldContainsFold(FieldGuildID, v))
}

// WelcomeTemplateEQ applies the EQ predicate on the "welcome_template" field.
func WelcomeTemplateEQ(v string) predicate.Guild {
	return predicate.Guild(sql.FieldEQ(FieldWelcomeTemplate, v))
}

// WelcomeTemplateNEQ applies the NEQ predicate on the "welcome_template" field.
func WelcomeTemplateNEQ(v string) predicate.Guild {
	return predicate.Guild(sql.FieldNEQ(FieldWelcomeTemplate, v))
}

// WelcomeTemplateIn applies the In predicate on the "welcome_template" field.
func WelcomeTemplateIn(vs ...string) predicate.Guild {
	return predicate.Guild(sql.FieldIn(FieldWelcomeTemplate, vs...))
}

// WelcomeTemplateNotIn applies the NotIn predicate on the "welcome_template" field.
func WelcomeTemplateNotIn(vs ...string) predicate.Guild {
	return predicate.Guild(sql.FieldNotIn(FieldWelcomeTemplate, vs...))
}

// WelcomeTemplateGT applies the GT predicate on the "welcome_template" field.
func WelcomeTemplateGT(v string) predicate.Guild {
	return predicate.Guild(sql.FieldGT(FieldWelcomeTemplate, v))
}

// WelcomeTemplateGTE applies the GTE predicate on the "welcome_template" field.
func WelcomeTemplateGTE(v string) predicate.Guild {
	return predicate.Guild(sql.FieldGTE(FieldWelcomeTemplate, v))
}

// WelcomeTemplateLT applies the LT predicate on the "welcome_template" field.
func WelcomeTemplateLT(v string) predicate.Guild {
	return predicate.Guild(sql.FieldLT(FieldWelcomeTemplate, v))
}

// WelcomeTemplateLTE applies the LTE predicate on the "welcome_template" field.
func WelcomeTemplateLTE(v string) predicate.Guild {
	return predicate.Guild(sql.FieldLTE(FieldWelcomeTemplate, v))
}

// WelcomeTemplateContains applies the Contains predicate on the "welcome_template" field.
func WelcomeTemplateContains(v string) predicate.Guild {
	return predicate.Guild(sql.FieldContains(FieldWelcomeTemplate, v))
}

// WelcomeTemplateHasPrefix applies the HasPrefix predicate on the "welcome_template" field.
func WelcomeTemplateHasPrefix(v string) predicate.Guild {
	return predicate.Guild(sql.FieldHasPrefix(FieldWelcomeTemplate, v))
}

// WelcomeTemplateHasSuffix applies the HasSuffix predicate on the "welcome_template" field.
func WelcomeTemplateHasSuffix(v string) predicate.Guild {
	return predicate.Guild(sql.FieldHasSuffix(FieldWelcomeTemplate, v))
}

// WelcomeTemplateEqualFold applies the EqualFold predicate on the "welcome_template" field.
func WelcomeTemplateEqualFold(v string) predicate.Guild {
	return predicate.Guild(sql.FieldEqualFold(FieldWelcomeTemplate, v))
}

// WelcomeTemplateContainsFold applies the ContainsFold predicate on the "welcome_template" field.
func WelcomeTemplateContainsFold(v string) predicate.Guild {
	return predicate.Guild(sql.FieldContainsFold(FieldWelcomeTemplate, v))
}

// WelcomeChannelEQ applies the EQ predicate on the "welcome_channel" field.
func WelcomeChannelEQ(v string) predicate.Guild {
	return predicate.Guild(sql.FieldEQ(FieldWelcomeChannel, v))
}

// WelcomeChannelNEQ applies the NEQ predicate on the "welcome_channel" field.
func WelcomeChannelNEQ(v string) predicate.Guild {
	return predicate.Guild(sql.FieldNEQ(FieldWelcomeChannel, v))
}

// WelcomeChannelIn applies the In predicate on the "welcome_channel" field.
func WelcomeChannelIn(vs ...string) predicate.Guild {
	return predicate.Guild(sql.FieldIn(FieldWelcomeChannel, vs...))
}

// WelcomeChannelNotIn applies the NotIn predicate on the "welcome_channel" field.
func WelcomeChannelNotIn(vs ...string) predicate.Guild {
	return predicate.Guild(sql.FieldNotIn(FieldWelcomeChannel, vs...))
}

// WelcomeChannelGT applies the GT predicate on the "welcome_channel" field.
func WelcomeChannelGT(v string) predicate.Guild {
	return predicate.Guild(sql.FieldGT(FieldWelcomeChannel, v))
}

// WelcomeChannelGTE applies the GTE predicate on the "welcome_channel" field.
func WelcomeChannelGTE(v string) predicate.Guild {
	return predicate.Guild(sql.FieldGTE(FieldWelcomeChannel, v))
}

// WelcomeChannelLT applies the LT predicate on the "welcome_channel" field.
func WelcomeChannelLT(v string) predicate.Guild {
	return predicate.Guild(sql.FieldLT(FieldWelcomeChannel, v))
}

// WelcomeChannelLTE applies the LTE predicate on the "welcome_channel" field.
func WelcomeChannelLTE(v string) predicate.Guild {
	return predicate.Guild(sql.FieldLTE(FieldWelcomeChannel, v))
}

// WelcomeChannelContains applies the Contains predicate on the "welcome_channel" field.
func WelcomeChannelContains(v string) predicate.Guild {
	return predicate.Guild(sql.FieldContains(FieldWelcomeChannel, v))
}

// WelcomeChannelHasPrefix applies the HasPrefix predicate on the "welcome_channel" field.
func WelcomeChannelHasPrefix(v string) predicate.Guild {
	return predicate.Guild(sql.FieldHasPrefix(FieldWelcomeChannel, v))
}

// WelcomeChannelHasSuffix applies the HasSuffix predicate on the "welcome_channel" field.
func WelcomeChannelHasSuffix(v string) predicate.Guild {
	return predicate.Guild(sql.FieldHasSuffix(FieldWelcomeChannel, v))
}

// WelcomeChannelEqualFold applies the EqualFold predicate on the "welcome_channel" field.
func WelcomeChannelEqualFold(v string) predicate.Guild {
	return predicate.Guild(sql.FieldEqualFold(FieldWelcomeChannel, v))
}

// WelcomeChannelContainsFold applies the ContainsFold predicate on the "welcome_channel" field.
func WelcomeChannelContainsFold(v string) predicate.Guild {
	return predicate.Guild(sql.FieldContainsFold(FieldWelcomeChannel, v))
}

// HasAutoRoleRules applies the HasEdge predicate on the "auto_role_rules" edge.
func HasAutoRoleRules() predicate.Guild {
	return predicate.Guild(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, AutoRoleRulesTable, AutoRoleRulesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAutoRoleRulesWith applies the HasEdge predicate on the "auto_role_rules" edge with a given conditions (other predicates).
func HasAutoRoleRulesWith(preds ...predicate.AutoRoleRule) predicate.Guild {
	return predicate.Guild(func(s *sql.Selector) {
		step := newAutoRoleRulesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Guild) predicate.Guild {
	return predicate.Guild(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Guild) predicate.Guild {
	return predicate.Guild(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Guild) predicate.Guild {
	return predicate.Guild(sql.NotPredicates(p))
}
