name: Deploy

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: Install dependencies
        run: go get .
      - name: Test
        run: go test -v .
      - name: Build
        run: go build .
      - name: Stop running instance of bot
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY}}
          script: sudo systemctl stop scotty
      - name: Install new binary
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.DEPLOY_USER }}
          server: ${{ secrets.DEPLOY_HOST }}
          ssh_private_key: ${{ secrets.DEPLOY_SSH_KEY }}
          local_path: "./scotty"
          remote_path: "/usr/local/bin/scotty"
      - name: Start new instance of bot
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY}}
          script: sudo systemctl start scotty
